name: kids-api
dependencies:
  - python=3.10.12
  - psycopg2==2.9.3
  - pip==23.3.1
  - pip:
    - alembic==1.12.1
    - apispec==6.3.0
    - Authlib==1.2.1
    - blinker==1.6.2
    - cffi==1.16.0
    - click==8.1.7
    - cryptography==41.0.5
    - Flask==3.0.0
    - Flask-Caching==1.10.1
    - Flask-Cors==3.0.10
    - Flask-JWT-Extended==4.5.3
    - Flask-Migrate==4.0.5
    - flask-smorest==0.42.2
    - Flask-SQLAlchemy==3.1.1
    - greenlet==2.0.2
    - itsdangerous==2.1.2
    - Jinja2==3.1.2
    - Mako==1.3.0
    - MarkupSafe==2.1.3
    - marshmallow==3.18.0
    - numpy==1.26.0
    - packaging==23.2
    - pandas==2.1.1
    - psycopg2-binary==2.9.7
    - pycparser==2.21
    - PyJWT==2.8.0
    - python-dateutil==2.8.2
    - python-decouple==3.8
    - python-dotenv==1.0.0
    - pytz==2023.3.post1
    - setuptools==68.0.0
    - six==1.16.0
    - SQLAlchemy==2.0.21
    - typing_extensions==4.8.0
    - tzdata==2023.3
    - webargs==8.3.0
    - Werkzeug==3.0.1
    - wheel==0.41.2