"""empty message

Revision ID: 8ddf12b078be
Revises: e71143136f17
Create Date: 2023-12-10 20:15:41.152014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '8ddf12b078be'
down_revision = 'e71143136f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presenca', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('motivo_presenca', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('meditacao', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('motivo_meditacao', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('versiculo', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('motivo_versiculo', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('culto', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('motivo_culto', sa.String(length=255), nullable=False))
        batch_op.drop_column('relatorio_culto')
        batch_op.drop_column('relatorio_versiculo')
        batch_op.drop_column('relatorio_presenca')
        batch_op.drop_column('relatorio_meditacao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relatorio_meditacao', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('relatorio_presenca', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('relatorio_versiculo', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('relatorio_culto', sqlite.JSON(), nullable=False))
        batch_op.drop_column('motivo_culto')
        batch_op.drop_column('culto')
        batch_op.drop_column('motivo_versiculo')
        batch_op.drop_column('versiculo')
        batch_op.drop_column('motivo_meditacao')
        batch_op.drop_column('meditacao')
        batch_op.drop_column('motivo_presenca')
        batch_op.drop_column('presenca')

    # ### end Alembic commands ###
