"""empty message

Revision ID: 9013f3e636ee
Revises: 8ddf12b078be
Create Date: 2023-12-10 21:41:02.482176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9013f3e636ee'
down_revision = '8ddf12b078be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crianca', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('data', sa.DateTime(), nullable=True))
        batch_op.drop_column('dataRelatorio')
        batch_op.drop_column('nomeCrianca')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nomeCrianca', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('dataRelatorio', sa.DATETIME(), nullable=True))
        batch_op.drop_column('data')
        batch_op.drop_column('crianca')

    # ### end Alembic commands ###
