"""empty message

Revision ID: a77d9377ee3b
Revises: 
Create Date: 2023-12-07 10:59:35.161578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77d9377ee3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nomeCrianca', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('dataRelatorio', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorios', schema=None) as batch_op:
        batch_op.drop_column('dataRelatorio')
        batch_op.drop_column('nomeCrianca')

    # ### end Alembic commands ###
