"""empty message

Revision ID: e71143136f17
Revises: a77d9377ee3b
Create Date: 2023-12-10 19:20:02.641446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e71143136f17'
down_revision = 'a77d9377ee3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relatorio_presenca', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('relatorio_meditacao', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('relatorio_versiculo', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('relatorio_culto', sqlite.JSON(), nullable=False))
        batch_op.drop_column('relatorio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relatorio', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('relatorio_culto')
        batch_op.drop_column('relatorio_versiculo')
        batch_op.drop_column('relatorio_meditacao')
        batch_op.drop_column('relatorio_presenca')

    # ### end Alembic commands ###
